// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "Simple-SNS": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/eniehack/simple-sns-go/design
// --out=D:\project\simple-sns-go
// --version=v1.3.1

package app
